version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    volumes:
      - ./:/var/www/html
    environment:
      - SYMFONY_ENV=dev
    ports:
      - "9001:9000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony_password
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs:ro
      - ./public:/var/www/html/public
    ports:
      - "443:443"
    depends_on:
      - php

volumes:
  db_data: